In [2]:
import pandas as pd

In [8]:
! ls htmlPages

10-10.html  11-29.html	12-6.html  3-18.html  5-10.html  6-30.html  8-23.html
10-11.html  1-12.html	1-27.html  3-19.html  5-11.html  6-3.html   8-24.html
10-12.html  11-2.html	12-7.html  3-1.html   5-12.html  6-4.html   8-25.html
10-13.html  11-30.html	1-28.html  3-20.html  5-13.html  6-5.html   8-26.html
10-14.html  1-13.html	12-8.html  3-21.html  5-14.html  6-6.html   8-27.html
10-15.html  11-3.html	1-29.html  3-22.html  5-15.html  6-7.html   8-28.html
10-16.html  1-14.html	12-9.html  3-23.html  5-16.html  6-8.html   8-29.html
10-17.html  11-4.html	1-2.html   3-24.html  5-17.html  6-9.html   8-2.html
10-18.html  1-15.html	1-30.html  3-25.html  5-18.html  7-10.html  8-30.html
10-19.html  11-5.html	1-31.html  3-26.html  5-19.html  7-11.html  8-31.html
10-1.html   1-16.html	1-3.html   3-27.html  5-1.html	 7-12.html  8-3.html
10-20.html  11-6.html	1-4.html   3-28.html  5-20.html  7-13.html  8-4.html
10-21.html  1-17.html	1-5.html   3-29.html  5-21.html  7-14.html  8-5.html
10-22.html  11-7.html	1-6.html   3-2.html   5-22.html  7-15.html  8-6.html
10-23.html  1-18.html	1-7.html   3-30.html  5-23.html  7-16.html  8-7.html
10-24.html  11-8.html	1-8.html   3-31.html  5-24.html  7-17.html  8-8.html
10-25.html  1-19.html	1-9.html   3-3.html   5-25.html  7-18.html  8-9.html
10-26.html  11-9.html	2-10.html  3-4.html   5-26.html  7-19.html  9-10.html
10-27.html  1-1.html	2-11.html  3-5.html   5-27.html  7-1.html   9-11.html
10-28.html  1-20.html	2-12.html  3-6.html   5-28.html  7-20.html  9-12.html
10-29.html  12-10.html	2-13.html  3-7.html   5-29.html  7-21.html  9-13.html
10-2.html   12-11.html	2-14.html  3-8.html   5-2.html	 7-22.html  9-14.html
10-30.html  12-12.html	2-15.html  3-9.html   5-30.html  7-23.html  9-15.html
10-31.html  12-13.html	2-16.html  4-10.html  5-31.html  7-24.html  9-16.html
10-3.html   12-14.html	2-17.html  4-11.html  5-3.html	 7-25.html  9-17.html
10-4.html   12-15.html	2-18.html  4-12.html  5-4.html	 7-26.html  9-18.html
10-5.html   12-16.html	2-19.html  4-13.html  5-5.html	 7-27.html  9-19.html
10-6.html   12-17.html	2-1.html   4-14.html  5-6.html	 7-28.html  9-1.html
10-7.html   12-18.html	2-20.html  4-15.html  5-7.html	 7-29.html  9-20.html
10-8.html   12-19.html	2-21.html  4-16.html  5-8.html	 7-2.html   9-21.html
10-9.html   1-21.html	2-22.html  4-17.html  5-9.html	 7-30.html  9-22.html
1-10.html   12-1.html	2-23.html  4-18.html  6-10.html  7-31.html  9-23.html
11-10.html  12-20.html	2-24.html  4-19.html  6-11.html  7-3.html   9-24.html
11-11.html  12-21.html	2-25.html  4-1.html   6-12.html  7-4.html   9-25.html
11-12.html  12-22.html	2-26.html  4-20.html  6-13.html  7-5.html   9-26.html
11-13.html  12-23.html	2-27.html  4-21.html  6-14.html  7-6.html   9-27.html
11-14.html  12-24.html	2-28.html  4-22.html  6-15.html  7-7.html   9-28.html
11-15.html  12-25.html	2-2.html   4-23.html  6-16.html  7-8.html   9-29.html
11-16.html  12-26.html	2-3.html   4-24.html  6-17.html  7-9.html   9-2.html
11-17.html  12-27.html	2-4.html   4-25.html  6-18.html  8-10.html  9-30.html
11-18.html  12-28.html	2-5.html   4-26.html  6-19.html  8-11.html  9-3.html
11-19.html  12-29.html	2-6.html   4-27.html  6-1.html	 8-12.html  9-4.html
1-11.html   1-22.html	2-7.html   4-28.html  6-20.html  8-13.html  9-5.html
11-1.html   12-2.html	2-8.html   4-29.html  6-21.html  8-14.html  9-6.html
11-20.html  12-30.html	2-9.html   4-2.html   6-22.html  8-15.html  9-7.html
11-21.html  12-31.html	3-10.html  4-30.html  6-23.html  8-16.html  9-8.html
11-22.html  1-23.html	3-11.html  4-3.html   6-24.html  8-17.html  9-9.html
11-23.html  12-3.html	3-12.html  4-4.html   6-25.html  8-18.html
11-24.html  1-24.html	3-13.html  4-5.html   6-26.html  8-19.html
11-25.html  12-4.html	3-14.html  4-6.html   6-27.html  8-1.html
11-26.html  1-25.html	3-15.html  4-7.html   6-28.html  8-20.html
11-27.html  12-5.html	3-16.html  4-8.html   6-29.html  8-21.html
11-28.html  1-26.html	3-17.html  4-9.html   6-2.html	 8-22.html

# Testing:

In [30]:
listOfTables=pd.read_html('htmlPages/5-20.html')
sampleDf=listOfTables[1]
sampleDf

,Unnamed: 0_level_0,Conditions,Comfort,Unnamed: 3_level_0,Unnamed: 4_level_0,Unnamed: 5_level_0,Unnamed: 6_level_0,Unnamed: 7_level_0,Unnamed: 8_level_0
,Time,Unnamed: 1_level_1,Temp,Weather,Wind,Unnamed: 5_level_1,Humidity,Barometer,Visibility
0,"00:14Sat, 20 May",NaN,20 °C,Passing clouds.,7 km/h,↑,100%,1016 mbar,14 km
1,00:54,NaN,20 °C,Partly cloudy.,No wind,↑,100%,1016 mbar,14 km
2,01:54,NaN,19 °C,Partly cloudy.,No wind,↑,100%,1015 mbar,13 km
3,02:54,NaN,19 °C,Passing clouds.,7 km/h,↑,100%,1016 mbar,14 km
4,03:54,NaN,19 °C,Partly cloudy.,No wind,↑,100%,1016 mbar,16 km
5,04:54,NaN,21 °C,Mostly cloudy.,17 km/h,↑,93%,1017 mbar,16 km
6,05:54,NaN,19 °C,Broken clouds.,17 km/h,↑,85%,1018 mbar,16 km
7,06:33,NaN,19 °C,Mostly cloudy.,13 km/h,↑,79%,1019 mbar,16 km
8,06:54,NaN,19 °C,Mostly cloudy.,15 km/h,↑,76%,1020 mbar,16 km
9,07:17,NaN,19 °C,Mostly cloudy.,19 km/h,↑,73%,1020 mbar,16 km
10,07:54,NaN,19 °C,Partly sunny.,11 km/h,↑,73%,1021 mbar,16 km
11,08:54,NaN,20 °C,Mostly cloudy.,22 km/h,↑,68%,1021 mbar,16 km
12,09:54,NaN,21 °C,Mostly cloudy.,22 km/h,↑,68%,1022 mbar,16 km
13,10:54,NaN,19 °C,Overcast.,19 km/h,↑,73%,1022 mbar,16 km
14,11:54,NaN,18 °C,Mostly cloudy.,17 km/h,↑,78%,1023 mbar,16 km
15,12:54,NaN,18 °C,Overcast.,24 km/h,↑,76%,1024 mbar,16 km
16,13:54,NaN,18 °C,Overcast.,22 km/h,↑,73%,1024 mbar,16 km
17,14:54,NaN,19 °C,Overcast.,22 km/h,↑,70%,1024 mbar,16 km
18,15:54,NaN,19 °C,Overcast.,20 km/h,↑,68%,1024 mbar,16 km
19,16:54,NaN,19 °C,Overcast.,19 km/h,↑,68%,1024 mbar,16 km
20,17:54,NaN,19 °C,Overcast.,19 km/h,↑,65%,1024 mbar,16 km
21,18:54,NaN,18 °C,Overcast.,22 km/h,↑,66%,1025 mbar,16 km
22,19:54,NaN,18 °C,Overcast.,22 km/h,↑,59%,1025 mbar,16 km
23,20:54,NaN,17 °C,Overcast.,13 km/h,↑,65%,1026 mbar,16 km
24,21:54,NaN,17 °C,Overcast.,19 km/h,↑,67%,1026 mbar,16 km
25,22:54,NaN,16 °C,Overcast.,15 km/h,↑,69%,1026 mbar,16 km
26,23:54,NaN,15 °C,Overcast.,11 km/h,↑,67%,1026 mbar,16 km
27,"* Reported 1 May 00:54 — 31 May 23:54, Baltimo...","Weather by CustomWeather, © 2019",NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [21]:
for name in sampleDf.columns:
    print(type(name))

<class 'tuple'>
<class 'tuple'>
<class 'tuple'>
<class 'tuple'>
<class 'tuple'>
<class 'tuple'>
<class 'tuple'>
<class 'tuple'>
<class 'tuple'>

In [72]:
humidity=(sampleDf[sampleDf.columns[6]])
humidity=humidity[humidity.notnull()]
humidity

0     100%
1     100%
2     100%
3     100%
4     100%
5      93%
6      85%
7      79%
8      76%
9      73%
10     73%
11     68%
12     68%
13     73%
14     78%
15     76%
16     73%
17     70%
18     68%
19     68%
20     65%
21     66%
22     59%
23     65%
24     67%
25     69%
26     67%
Name: (Unnamed: 6_level_0, Humidity), dtype: object

In [75]:
humidity=(sampleDf[sampleDf.columns[6]])
humidity =humidity.drop(0)
humidity =humidity.drop(len(humidity))
# for i in range(len(humidity)):
#     s=humidity.loc[i]
#     print(int(s[:-1]))

humidity=humidity[humidity.notnull()]
humidity=humidity.map(lambda x: int(x[:-1]))
humidity.mean()

76.11538461538461

# seeing if can merge with current data:

In [43]:
# import os
# files=os.listdir('htmlPages')
ground=pd.read_csv('ground.csv')
ground['TIMESTAMP'] = ground['TIMESTAMP'].map(lambda x: str(x)[:-6])
ground

,Unnamed: 0,TIMESTAMP,Pyra1_Wm2_Avg,Pyra2_Wm2_Avg,RECORD,AmbTemp_C_Avg,InvPAC_kW_Avg,InvPDC_kW_Avg,PwrMtrP_kW_Avg
0,0,2017-09-01 00:00:00,-8.791522,-3.418324,565528.0,20.300,0.0,0.0,0.0
1,1,2017-09-01 00:01:00,-8.791522,-3.418324,565529.0,20.350,0.0,0.0,0.0
2,2,2017-09-01 00:02:00,-9.029131,-3.418324,565530.0,20.330,0.0,0.0,0.0
3,3,2017-09-01 00:03:00,-9.147935,-3.418324,565531.0,20.260,0.0,0.0,0.0
4,4,2017-09-01 00:04:00,-9.147935,-3.418324,565532.0,20.260,0.0,0.0,0.0
5,5,2017-09-01 00:05:00,-9.147935,-3.642477,565533.0,20.230,0.0,0.0,0.0
6,6,2017-09-01 00:06:00,-9.266739,-3.866629,565534.0,20.250,0.0,0.0,0.0
7,7,2017-09-01 00:07:00,-9.504348,-3.866629,565535.0,20.210,0.0,0.0,0.0
8,8,2017-09-01 00:08:00,-9.504348,-3.866629,565536.0,20.200,0.0,0.0,0.0
9,9,2017-09-01 00:09:00,-9.385544,-3.866629,565537.0,20.170,0.0,0.0,0.0
10,10,2017-09-01 00:10:00,-9.147935,-3.754553,565538.0,20.130,0.0,0.0,0.0
11,11,2017-09-01 00:11:00,-9.147935,-3.642477,565539.0,20.170,0.0,0.0,0.0
12,12,2017-09-01 00:12:00,-9.147935,-3.642477,565540.0,20.150,0.0,0.0,0.0
13,13,2017-09-01 00:13:00,-9.147935,-3.754553,565541.0,20.150,0.0,0.0,0.0
14,14,2017-09-01 00:14:00,-9.147935,-3.866629,565542.0,20.160,0.0,0.0,0.0
15,15,2017-09-01 00:15:00,-9.147935,-3.642477,565543.0,20.120,0.0,0.0,0.0
16,16,2017-09-01 00:16:00,-9.147935,-3.418324,565544.0,20.110,0.0,0.0,0.0
17,17,2017-09-01 00:17:00,-9.147935,-3.418324,565545.0,20.130,0.0,0.0,0.0
18,18,2017-09-01 00:18:00,-9.147935,-3.418324,565546.0,20.080,0.0,0.0,0.0
19,19,2017-09-01 00:19:00,-9.147935,-3.418324,565547.0,20.100,0.0,0.0,0.0
20,20,2017-09-01 00:20:00,-9.266739,-3.642477,565548.0,20.040,0.0,0.0,0.0
21,21,2017-09-01 00:21:00,-9.504348,-3.866629,565549.0,20.020,0.0,0.0,0.0
22,22,2017-09-01 00:22:00,-9.741957,-3.866629,565550.0,20.010,0.0,0.0,0.0
23,23,2017-09-01 00:23:00,-9.979566,-3.978705,565551.0,20.010,0.0,0.0,0.0
24,24,2017-09-01 00:24:00,-9.979566,-4.202858,565552.0,20.040,0.0,0.0,0.0
25,25,2017-09-01 00:25:00,-9.979566,-4.202858,565553.0,20.020,0.0,0.0,0.0
26,26,2017-09-01 00:26:00,-9.741957,-3.866629,565554.0,19.970,0.0,0.0,0.0
27,27,2017-09-01 00:27:00,-9.504348,-3.866629,565555.0,19.940,0.0,0.0,0.0
28,28,2017-09-01 00:28:00,-9.504348,-3.866629,565556.0,19.930,0.0,0.0,0.0
29,29,2017-09-01 00:29:00,-9.504348,-3.866629,565557.0,19.960,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...
525570,525570,2017-10-31 23:30:00,-10.335979,-4.539087,651927.0,6.303,0.0,0.0,0.0
525571,525571,2017-10-31 23:31:00,-10.335979,-4.539087,651928.0,6.378,0.0,0.0,0.0
525572,525572,2017-10-31 23:32:00,-10.335979,-4.539087,651929.0,6.324,0.0,0.0,0.0
525573,525573,2017-10-31 23:33:00,-10.098370,-4.427010,651930.0,6.327,0.0,0.0,0.0
525574,525574,2017-10-31 23:34:00,-9.979566,-4.539087,651931.0,6.402,0.0,0.0,0.0
525575,525575,2017-10-31 23:35:00,-9.979566,-4.539087,651932.0,6.416,0.0,0.0,0.0
525576,525576,2017-10-31 23:36:00,-9.741957,-4.314934,651933.0,6.400,0.0,0.0,0.0
525577,525577,2017-10-31 23:37:00,-9.504348,-4.539087,651934.0,6.343,0.0,0.0,0.0
525578,525578,2017-10-31 23:38:00,-9.741957,-4.539087,651935.0,6.300,0.0,0.0,0.0
525579,525579,2017-10-31 23:39:00,-10.335979,-4.539087,651936.0,6.377,0.0,0.0,0.0
525580,525580,2017-10-31 23:40:00,-10.335979,-4.539087,651937.0,6.332,0.0,0.0,0.0
525581,525581,2017-10-31 23:41:00,-10.335979,-4.539087,651938.0,6.201,0.0,0.0,0.0
525582,525582,2017-10-31 23:42:00,-10.454783,-4.763239,651939.0,6.194,0.0,0.0,0.0
525583,525583,2017-10-31 23:43:00,-10.930001,-4.987391,651940.0,6.106,0.0,0.0,0.0
525584,525584,2017-10-31 23:44:00,-10.454783,-4.651163,651941.0,6.205,0.0,0.0,0.0
525585,525585,2017-10-31 23:45:00,-10.335979,-4.651163,651942.0,6.199,0.0,0.0,0.0
525586,525586,2017-10-31 23:46:00,-10.335979,-4.651163,651943.0,6.324,0.0,0.0,0.0
525587,525587,2017-10-31 23:47:00,-10.335979,-4.539087,651944.0,6.414,0.0,0.0,0.0
525588,525588,2017-10-31 23:48:00,-10.335979,-4.539087,651945.0,6.595,0.0,0.0,0.0
525589,525589,2017-10-31 23:49:00,-10.335979,-4.539087,651946.0,6.559,0.0,0.0,0.0
525590,525590,2017-10-31 23:50:00,-10.335979,-4.539087,651947.0,6.619,0.0,0.0,0.0
525591,525591,2017-10-31 23:51:00,-10.335979,-4.314934,651948.0,6.493,0.0,0.0,0.0
525592,525592,2017-10-31 23:52:00,-10.335979,-4.090782,651949.0,6.440,0.0,0.0,0.0
525593,525593,2017-10-31 23:53:00,-9.623153,-3.866629,651950.0,6.381,0.0,0.0,0.0
525594,525594,2017-10-31 23:54:00,-9.504348,-4.202858,651951.0,6.374,0.0,0.0,0.0
525595,525595,2017-10-31 23:55:00,-9.979566,-4.539087,651952.0,6.451,0.0,0.0,0.0
525596,525596,2017-10-31 23:56:00,-10.335979,-4.427010,651953.0,6.547,0.0,0.0,0.0
525597,525597,2017-10-31 23:57:00,-9.741957,-3.978705,651954.0,6.529,0.0,0.0,0.0
525598,525598,2017-10-31 23:58:00,-9.504348,-3.866629,651955.0,6.628,0.0,0.0,0.0
525599,525599,2017-10-31 23:59:00,-9.504348,-3.866629,651956.0,6.659,0.0,0.0,0.0

In [44]:
timestamp=pd.DataFrame(ground.TIMESTAMP)
timestamp

                  TIMESTAMP
0       2017-09-01 00:00:00
1       2017-09-01 00:01:00
2       2017-09-01 00:02:00
3       2017-09-01 00:03:00
4       2017-09-01 00:04:00
5       2017-09-01 00:05:00
6       2017-09-01 00:06:00
7       2017-09-01 00:07:00
8       2017-09-01 00:08:00
9       2017-09-01 00:09:00
10      2017-09-01 00:10:00
11      2017-09-01 00:11:00
12      2017-09-01 00:12:00
13      2017-09-01 00:13:00
14      2017-09-01 00:14:00
15      2017-09-01 00:15:00
16      2017-09-01 00:16:00
17      2017-09-01 00:17:00
18      2017-09-01 00:18:00
19      2017-09-01 00:19:00
20      2017-09-01 00:20:00
21      2017-09-01 00:21:00
22      2017-09-01 00:22:00
23      2017-09-01 00:23:00
24      2017-09-01 00:24:00
25      2017-09-01 00:25:00
26      2017-09-01 00:26:00
27      2017-09-01 00:27:00
28      2017-09-01 00:28:00
29      2017-09-01 00:29:00
...                     ...
525570  2017-10-31 23:30:00
525571  2017-10-31 23:31:00
525572  2017-10-31 23:32:00
525573  2017-10-31 23:33:00
525574  2017-10-31 23:34:00
525575  2017-10-31 23:35:00
525576  2017-10-31 23:36:00
525577  2017-10-31 23:37:00
525578  2017-10-31 23:38:00
525579  2017-10-31 23:39:00
525580  2017-10-31 23:40:00
525581  2017-10-31 23:41:00
525582  2017-10-31 23:42:00
525583  2017-10-31 23:43:00
525584  2017-10-31 23:44:00
525585  2017-10-31 23:45:00
525586  2017-10-31 23:46:00
525587  2017-10-31 23:47:00
525588  2017-10-31 23:48:00
525589  2017-10-31 23:49:00
525590  2017-10-31 23:50:00
525591  2017-10-31 23:51:00
525592  2017-10-31 23:52:00
525593  2017-10-31 23:53:00
525594  2017-10-31 23:54:00
525595  2017-10-31 23:55:00
525596  2017-10-31 23:56:00
525597  2017-10-31 23:57:00
525598  2017-10-31 23:58:00
525599  2017-10-31 23:59:00

[525600 rows x 1 columns]

In [78]:
import re
d={'Humidity':[]}
cache=0
cacheId=0
for i in range(len(timestamp)):
    s=timestamp.loc[i][0]
    patternStr=r'-(\d+)'
    L=re.findall(patternStr,s)
    fileName='-'.join([re.sub(r'0(\d)',r'\1',x) for x in L]) # using regex groups: converting type 01 -> 1, 10 -> 10
    table= pd.read_html('htmlPages/{}.html'.format(fileName))[1]

    humidity=table[table.columns[6]]
    humidity =humidity.drop(0);humidity =humidity.drop(len(humidity))
    humidity=humidity[humidity.notnull()]
    humidity=humidity.map(lambda x: int(x[:-1]))
    d['Humidity'].append(humidity.mean())

humidityDf=pd.DataFrame(d)
humidityDf

KeyboardInterrupt:

In [74]:
pd.DataFrame?